SUPABASE_URL="https://bbujprlezxkvjnotuyiq.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidWpwcmxlenhrdmpub3R1eWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyNDQ0NDAsImV4cCI6MjA5ODgyMDQ0MH0.QNZa4P4lRBIODdqrkqjaSuXV5qGyr4yTKm0xkRyjVNk"
